apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL for Let’s Encrypt’s production environment
    server: https://acme-v02.api.letsencrypt.org/directory
    # Replace this email with your email address for notifications
    email: support@swadesi.style
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx