apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-swadesi
spec:
  ingressClassName: nginx
  rules:
    - host: swadesi.style
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 3000
    - host: www.swadesi.style
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 3000